#ifndef CORE_CONFIG_HEADER
#define CORE_CONFIG_HEADER


// behaviour
#define LOG_STRICTNESS_CONSERVATIVE 1

// gpu
#define GPU_BUFFER_COUNT 2

// blitter
#define FRAME_PROGRAM_TITLE "C. Hansen's Counter-Clockwork"
#define FRAME_BLITTER_VSYNC false
#define FRAME_RESOLUTION_X 1600
#define FRAME_RESOLUTION_Y 900
#define FRAME_TIME_BUDGET_MS 15.
#define FRAME_BLITTER_SWAP_IMAGES 1

// buffer
#define BUFFER_UNIFORM_ALLOCATION_SIZE 4096
#define BUFFER_MAXIMUM_TEXTURE_COUNT 1024
#define BUFFER_ATLAS_BORDER_PADDING 32

// renderer
#define RENDERER_SPRITE_MEMORY_WIDTH 2048
#define RENDERER_SPRITE_MEMORY_HEIGHT 2048
#define RENDERER_FONT_MEMORY_WIDTH 2048
#define RENDERER_FONT_MEMORY_HEIGHT 2048
#define RENDERER_MAXIMUM_TEXTURE_COUNT 2048
#define RENDERER_MAXIMUM_CHARACTER_COUNT 4096
#define RENDERER_MAXIMUM_FONT_COUNT 2
#define RENDERER_SHADOW_RESOLUTION 2048
#define RENDERER_SHADOW_RANGE 25

// TODO define in extern config file and store constants at runtime


#endif
