#ifndef CORE_CONFIG_HEADER
#define CORE_CONFIG_HEADER


// blitter
#define FRAME_BLITTER_VSYNC true
#define FRAME_RESOLUTION_X 1600
#define FRAME_RESOLUTION_Y 900
#define FRAME_TIME_BUDGET_MS 15.
#define FRAME_BLITTER_SWAP_IMAGES 1

// buffer
#define BUFFER_MAXIMUM_TEXTURE_COUNT 1024
#define BUFFER_ATLAS_BORDER_PADDING 32

// renderer
#define RENDERER_SPRITE_MEMORY_WIDTH 2048
#define RENDERER_SPRITE_MEMORY_HEIGHT 2048
#define RENDERER_FONT_MEMORY_WIDTH 2048
#define RENDERER_FONT_MEMORY_HEIGHT 2048
#define RENDERER_MAXIMUM_TEXTURE_COUNT 2048
#define RENDERER_MAXIMUM_FONT_COUNT 2
#define RENDERER_SHADOW_RESOLUTION 4096
#define RENDERER_SHADOW_RANGE 150

// TODO define in extern config file and store constants at runtime


#endif
